- name: bench_pre_approach
  frame_id: bench_lid
  tx: 0.737
  ty: 0.55
  tz: -0.030
  rx: 0.5
  ry: 0.5
  rz: -0.5
  rw: -0.5
- name: bench_approach
  frame_id: bench_lid
  tx: 0.592
  ty: 0.55
  tz: -0.030
  rx: 0.5
  ry: 0.5
  rz: -0.5
  rw: -0.5
- name: bench_close_approach
  frame_id: bench_lid
  tx: 0.598
  ty: 0.545
  tz: -0.019
  rx: 0.033
  ry: -0.551
  rz: 0.023
  rw: 0.833
- name: bench_close_pre_approach
  frame_id: bench_lid
  tx: 0.620
  ty: 0.547
  tz: -0.029
  rx: 0.033
  ry: -0.551
  rz: 0.023
  rw: 0.833
- name: bench_close_retreat
  frame_id: bench_lid
  tx: -0.04
  ty: 0.551
  tz: -0.660
  rx: 0.04
  ry: 0.197
  rz: -0.007
  rw: 0.980
- name: bench_close_retreat_retreat
  frame_id: bench_lid
  tx: 0.1
  ty: 0.551
  tz: -0.760
  rx: 0.04
  ry: 0.197
  rz: -0.007
  rw: 0.980
- name: bench_place_pre_approach
  frame_id: bench_back
  tx: 0.42
  ty: 1.0
  tz: 0.9
  rx: 0.707
  ry: 0.707
  rz: 0.0
  rw: 0.0
- name: bench_place_approach
  frame_id: bench_back
  tx: 0.42
  ty: 0.65
  tz: 0.9
  rx: 0.707
  ry: 0.707
  rz: 0.0
  rw: 0.0
- name: bench_place_location
  frame_id: bench_back
  tx: 0.42
  ty: 0.65
  tz: 0.1
  rx: 0.707
  ry: 0.707
  rz: 0.0
  rw: 0.0
- name: bench_place_retreat
  frame_id: bench_back
  tx: 0.42
  ty: 0.65
  tz: 0.2
  rx: 0.707
  ry: 0.707
  rz: 0.0
  rw: 0.0
- name: bench_open_retreat
  frame_id: bench_back
  tx: 0.516
  ty: 0.417
  tz: 0.825
  rx: 0.601
  ry: 0.634
  rz: -0.360
  rw: -0.328
