- name: new_transform_1
  frame_id: parent_transform_1
  tx: 0.05
  ty: -0.09
  tz: 0.0
  rx: 0.7071067
  ry: 0.0
  rz: -0.7071067
  rw: 0.0
- name: new_transform_1
  frame_id: parent_transform_1
  tx: 0.12
  ty: -0.09
  tz: 0.0
  rx: 0.7071067
  ry: 0.0
  rz: -0.7071067
  rw: 0.0
- name: new_transform_2
  frame_id: parent_transform_2
  tx: -0.15
  ty: -1.200
  tz: 0.95
  rx: -0.5
  ry: -0.5
  rz: -0.5
  rw: 0.5
- name: new_transform_2
  frame_id: parent_transform_2
  tx: -0.076
  ty: -1.140
  tz: 0.95
  rx: 0.527
  ry: 0.485
  rz: 0.559
  rw: -0.418
- name: new_transform_3
  frame_id: parent_transform_3
  tx: 0.792
  ty: 0.462
  tz: 0.981
  rx: 0.5
  ry: 0.5
  rz: 0.5
  rw: -0.5
- name: new_transform_3
  frame_id: parent_transform_3
  tx: 0.791
  ty: 0.828
  tz: 0.981
  rx: 0.5
  ry: 0.5
  rz: 0.5
  rw: -0.5
- name: new_transform_4
  frame_id: parent_transform_4
  tx: 0.05
  ty: -0.09
  tz: 0.0
  rx: 0.7071067
  ry: 0.0
  rz: -0.7071067
  rw: 0.0
- name: new_transform_4
  frame_id: parent_transform_4
  tx: 0.12
  ty: -0.09
  tz: 0.0
  rx: 0.7071067
  ry: 0.0
  rz: -0.7071067
  rw: 0.0
