- name: open_handle_grasp
  frame_id: external_grab_handle
  tx: 0.05
  ty: -0.09
  tz: 0.0
  rx: 0.0
  ry: -0.7071067
  rz: 0.0
  rw: 0.7071067
- name: open_handle_approach
  frame_id: external_grab_handle
  tx: 0.25
  ty: -0.09
  tz: 0.0
  rx: 0.0
  ry: -0.7071067
  rz: 0.0
  rw: 0.7071067
- name: open_avoid_door
  frame_id: hatch_4040_face
  tx: -0.15
  ty: -1.200
  tz: 0.0
  rx: -0.5
  ry: -0.5
  rz: -0.5
  rw: 0.5
- name: open_door_contact
  frame_id: hatch_4040_face
  tx: -0.076
  ty: -1.140
  tz: 0.0
  rx: 0.527
  ry: 0.485
  rz: 0.559
  rw: -0.418