- name: hatch_interior_place_approach
  frame_id: hatch_outer_frame
  tx: -0.351
  ty: 0.657
  tz: 0.0
  rx: 0.707
  ry: 0.707
  rz: 0.0
  rw: 0.0
- name: hatch_interior_place_location
  frame_id: hatch_outer_frame
  tx: -0.351
  ty: 0.657
  tz: -0.109
  rx: 0.707
  ry: 0.707
  rz: 0.0
  rw: 0.0