- name: external_rotary_wheel_far_approach
  tx: 0.0
  ty: 0.0
  tz: 0.1
  rx: 0.0
  ry: 1.0
  rz: 0.0
  rw: 0.0
  frame_id: external_rotary_wheel
- name: external_rotary_wheel_approach
  tx: 0.0
  ty: 0.0
  tz: 0.05
  rx: 0.0
  ry: 1.0
  rz: 0.0
  rw: 0.0
  frame_id: external_rotary_wheel
- name: external_rotary_wheel_grasp
  tx: 0.0
  ty: 0.0
  tz: 0.02
  rx: 0.0
  ry: 1.0
  rz: 0.0
  rw: 0.0
  frame_id: external_rotary_wheel