- name: grab_handle_grasp_frame
  frame_id: external_grab_handle
  tx: 0.05
  ty: -0.09
  tz: 0.0
  rx: 0.0
  ry: -0.7071067
  rz: 0.0
  rw: 0.7071067
- name: grab_handle_approach2
  frame_id: external_grab_handle
  tx: 0.0
  ty: 0.1
  tz: 0.0
  rx: 0.0
  ry: 0.0
  rz: 0.0
  rw: 1.0