- name: grab_handle_approach
  tx: 0.1
  ty: 0.0
  tz: 0.0
  rx: 0.0
  ry: 0.0
  rz: 0.0
  rw: 1.0
  frame_id: external_exterior_grab_handle
- name: grab_handle_approach2
  tx: 0.0
  ty: 0.1
  tz: 0.0
  rx: 0.0
  ry: 0.0
  rz: 0.0
  rw: 1.0
  frame_id: external_exterior_grab_handle