- name: intermediate_place_approach
  frame_id: bench_back
  tx: 0.055
  ty: 1.390
  tz: 0.236
  rx: 0.707
  ry: 0.707
  rz: 0.0
  rw: 0.0
- name: intermediate_place_location
  frame_id: bench_back
  tx: 0.055
  ty: 1.390
  tz: 0.136
  rx: 0.707
  ry: 0.707
  rz: 0.0
  rw: 0.0