- name: proto_handle_location
  frame_id: hatch_face
  tx: -0.153
  ty: -0.157
  tz: 0.438
  rx: 0.5
  ry: -0.5
  rz: 0.5
  rw: -0.5
<<<<<<< HEAD
- name: hatch_hinge_handle_grasp
  frame_id: hatch_face
  tx: -0.147
  ty: -0.125
  tz: 0.620
  rx: -0.5
  ry: 0.5
  rz: -0.5
  rw: 0.5
- name: hatch_hinge_handle_approach
  frame_id: hatch_face
  tx: -0.227
  ty: -0.127
  tz: 0.620
  rx: -0.5
  ry: 0.5
  rz: -0.5
  rw: 0.5
=======
- name: external_3_handle_grasp
  frame_id: external_3_grab_handle
  tx: 0.05
  ty: -0.15
  tz: 0.0
  rx: 0.7071067
  ry: 0.0
  rz: -0.7071067
  rw: 0.0
- name: external_3_handle_approach
  frame_id: external_3_grab_handle
  tx: 0.12
  ty: -0.15
  tz: 0.0
  rx: 0.7071067
  ry: 0.0
  rz: -0.7071067
  rw: 0.0
>>>>>>> 933506dd577efe3a66d98ab31f831061bae30170
