- name: open_handle_grasp
  frame_id: internal_grab_handle
  tx: 0.055
  ty: -0.09
  tz: 0.0
  rx: 0.7071067
  ry: 0.0
  rz: -0.7071067
  rw: 0.0
- name: open_handle_approach
  frame_id: internal_grab_handle
  tx: 0.12
  ty: -0.09
  tz: 0.0
  rx: 0.7071067
  ry: 0.0
  rz: -0.7071067
  rw: 0.0
- name: open_avoid_door
  frame_id: hatch_face
  tx: -0.096
  ty: -0.943
  tz: 0.926
  rx: -0.653
  ry: 0.699
  rz: 0.234
  rw: -0.172
- name: open_door_contact
  frame_id: hatch_face
  tx: -0.076
  ty: -1.140
  tz: 0.0
  rx: 0.527
  ry: 0.485
  rz: 0.559
  rw: -0.418
- name: open_door_2_retreat
  frame_id: hatch_outer_frame
  tx: 0.792
  ty: 0.462
  tz: 0.981
  rx: 0.5
  ry: 0.5
  rz: 0.5
  rw: -0.5
- name: open_door_3_start
  frame_id: hatch_outer_frame
  tx: 0.791
  ty: 0.828
  tz: 0.981
  rx: 0.5
  ry: 0.5
  rz: 0.5
  rw: -0.5
- name: close_handle_grasp
  frame_id: external_grab_handle
  tx: 0.05
  ty: -0.09
  tz: 0.0
  rx: 0.7071067
  ry: 0.0
  rz: -0.7071067
  rw: 0.0
- name: close_handle_approach
  frame_id: external_grab_handle
  tx: 0.12
  ty: -0.09
  tz: 0.0
  rx: 0.7071067
  ry: 0.0
  rz: -0.7071067
  rw: 0.0
- name: close_avoid_door
  frame_id: hatch_face
  tx: 0.075
  ty: -1.1
  tz: 0.95
  rx: -0.5
  ry: -0.5
  rz: -0.5
  rw: 0.5
- name: close_door_contact
  frame_id: hatch_face
  tx: -0.020
  ty: -1.140
  tz: 0.95
  rx: 0.527
  ry: 0.485
  rz: 0.559
  rw: -0.418
- name: close_door_retreat
  frame_id: hatch_outer_frame
  tx: 0.318
  ty: 0.284
  tz: 1.028
  rx: -0.273
  ry: -0.662
  rz: -0.330
  rw: 0.615
- name: hatch_interior_place_approach
  frame_id: hatch_outer_frame
  tx: -0.351
  ty: 0.657
  tz: 0.0
  rx: 0.707
  ry: 0.707
  rz: 0.0
  rw: 0.0
- name: hatch_interior_place_location
  frame_id: hatch_outer_frame
  tx: -0.351
  ty: 0.657
  tz: -0.109
  rx: 0.707
  ry: 0.707
  rz: 0.0
  rw: 0.0
- name: external_rotary_wheel_far_approach
  tx: 0.0
  ty: 0.0
  tz: 0.2
  rx: 0.0
  ry: 1.0
  rz: 0.0
  rw: 0.0
  frame_id: external_rotary_wheel
- name: external_rotary_wheel_approach
  tx: 0.0
  ty: 0.0
  tz: 0.05
  rx: 0.0
  ry: 1.0
  rz: 0.0
  rw: 0.0
  frame_id: external_rotary_wheel
- name: external_rotary_wheel_grasp
  tx: 0.0
  ty: 0.0
  tz: 0.02
  rx: 0.0
  ry: 1.0
  rz: 0.0
  rw: 0.0
  frame_id: external_rotary_wheel
- name: internal_rotary_wheel_far_approach
  tx: 0.0
  ty: 0.0
  tz: 0.2
  rx: 0.0
  ry: 1.0
  rz: 0.0
  rw: 0.0
  frame_id: internal_rotary_wheel
- name: internal_rotary_wheel_approach
  tx: 0.0
  ty: 0.0
  tz: 0.05
  rx: 0.0
  ry: 1.0
  rz: 0.0
  rw: 0.0
  frame_id: internal_rotary_wheel
- name: internal_rotary_wheel_grasp
  tx: 0.0
  ty: 0.0
  tz: 0.02
  rx: 0.0
  ry: 1.0
  rz: 0.0
  rw: 0.0
  frame_id: internal_rotary_wheel
- name: external_rotary_handle_grasp_forward
  tx: 0.0
  ty: 0.0
  tz: 0.0
  rx: -0.7071068
  ry: 0.7071068
  rz: 0.0
  rw: 0.0
  frame_id: external_rotary_handle_grasp
- name: external_rotary_handle_grasp_side
  tx: 0.0
  ty: 0.0
  tz: 0.0
  rx: 0.0
  ry: -0.7071068
  rz: 0.7071068
  rw: 0.0
  frame_id: external_rotary_handle_grasp
- name: external_rotary_handle_grasp_approach
  tx: 0.0
  ty: 0.0
  tz: 0.05
  rx: -0.7071068
  ry: 0.7071068
  rz: 0.0
  rw: 0.0
  frame_id: external_rotary_handle_grasp
- name: external_rotary_handle_grasp_far
  tx: 0.0
  ty: 0.0
  tz: 1.0
  rx: -0.7071068
  ry: 0.7071068
  rz: 0.0
  rw: 0.0
  frame_id: external_rotary_handle_grasp
- name: external_rotary_handle_unfold_grasp
  tx: 0.0
  ty: 0.0
  tz: 0.0
  rx: 0.0
  ry: -0.7071068
  rz: 0.7071068
  rw: 0.0
  frame_id: external_rotary_handle_grasp
- name: external_rotary_handle_unfold_approach
  tx: 0.0
  ty: 0.5
  tz: 0.0
  rx: 0.0
  ry: -0.7071068
  rz: 0.7071068
  rw: 0.0
  frame_id: external_rotary_handle_grasp
- name: proto_handle_location
  frame_id: hatch_face
  tx: -0.153
  ty: -0.157
  tz: 0.438
  rx: 0.5
  ry: -0.5
  rz: 0.5
  rw: -0.5
- name: hatch_hinge_handle_grasp
  frame_id: hatch_face
  tx: -0.147
  ty: -0.125
  tz: 0.620
  rx: -0.5
  ry: 0.5
  rz: -0.5
  rw: 0.5
- name: hatch_hinge_handle_approach
  frame_id: hatch_face
  tx: -0.227
  ty: -0.127
  tz: 0.620
  rx: -0.5
  ry: 0.5
  rz: -0.5
  rw: 0.5